"""PRD / version planning from grounded findings."""

from __future__ import annotations

from typing import Any

from app.prompts.prd import PRD_SYSTEM_PROMPT, build_prd_user_prompt
from app.services.moonshot_client import MoonshotClient, MoonshotError


def _compact_findings(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    compact = []
    for finding in findings[:6]:
        review_ids = [str(r) for r in (finding.get("evidence_review_ids") or [])][:6]
        compact.append(
            {
                "finding_id": finding.get("finding_id"),
                "title": str(finding.get("title") or "")[:80],
                "summary": str(finding.get("summary") or "")[:180],
                "severity": finding.get("severity"),
                "support_count": finding.get("support_count"),
                "confidence": finding.get("confidence"),
                "assumption": bool(finding.get("assumption", False)),
                "evidence_review_ids": review_ids,
            }
        )
    return compact


def _priority_for_finding(finding: dict[str, Any]) -> tuple[str, str]:
    severity = str(finding.get("severity") or "medium").lower()
    assumption = bool(finding.get("assumption", False))
    confidence = float(finding.get("confidence") or 0)
    support = int(finding.get("support_count") or 0)

    if assumption or confidence < 0.55 or support < 2:
        return "P2", "Research"
    if severity == "high" or (support >= 4 and confidence >= 0.75):
        return "P0", "vNext-1"
    if severity == "medium":
        return "P1", "vNext-2"
    return "P2", "Research"


def _fallback_prd_from_findings(
    findings: list[dict[str, Any]],
    goal: str | None,
) -> dict[str, Any]:
    requirements: list[dict[str, Any]] = []
    for index, finding in enumerate(findings[:5]):
        fid = str(finding.get("finding_id") or f"f{index + 1}")
        review_ids = [str(r) for r in (finding.get("evidence_review_ids") or [])]
        if not review_ids:
            continue
        priority, version = _priority_for_finding(finding)
        title = str(finding.get("title") or f"Requirement {index + 1}")
        requirements.append(
            {
                "req_id": f"R{index + 1}",
                "title": title[:100],
                "description": str(finding.get("summary") or title)[:300],
                "user_problem": title[:160],
                "priority": priority,
                "version": version,
                "linked_finding_ids": [fid],
                "linked_review_ids": review_ids,
                "acceptance_criteria": [
                    f"Issue described in finding {fid} is measurably improved",
                    "Linked review themes no longer dominate new low-rating feedback",
                ],
                "non_goals": ["Do not invent features unrelated to linked findings"],
                "origin": "rule",
            }
        )

    req_ids_by_version = {"vNext-1": [], "vNext-2": [], "Research": []}
    for req in requirements:
        req_ids_by_version.setdefault(req["version"], []).append(req["req_id"])

    focus = goal or "product improvement from review findings"
    return {
        "title": f"PRD for {focus}"[:120],
        "background": "Generated by deterministic fallback after model JSON failure.",
        "goals": [focus],
        "non_goals": ["Invent requirements without review evidence"],
        "version_plan": [
            {
                "version": "vNext-1",
                "focus": "Highest-priority high-evidence fixes",
                "req_ids": req_ids_by_version["vNext-1"],
            },
            {
                "version": "vNext-2",
                "focus": "Important follow-ups",
                "req_ids": req_ids_by_version["vNext-2"],
            },
            {
                "version": "Research",
                "focus": "Weak-evidence items to investigate",
                "req_ids": req_ids_by_version["Research"],
            },
        ],
        "requirements": requirements,
        "risks": ["Model PRD unavailable; fallback may be less nuanced"],
        "open_questions": ["Re-run plan stage when Moonshot JSON is stable"],
        "success_metrics": ["Fewer low-rating reviews on linked themes"],
    }


def _validate_prd(
    raw_prd: dict[str, Any],
    findings: list[dict[str, Any]],
    *,
    origin_default: str = "model",
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    finding_by_id = {
        str(f.get("finding_id")): f for f in findings if f.get("finding_id")
    }
    rejected: list[dict[str, Any]] = []
    requirements: list[dict[str, Any]] = []

    raw_requirements = raw_prd.get("requirements") or []
    if not isinstance(raw_requirements, list):
        raise MoonshotError("PRD JSON missing requirements array")

    for index, item in enumerate(raw_requirements):
        if not isinstance(item, dict):
            rejected.append({"reason": "not_an_object", "raw": item})
            continue

        linked_findings = [
            str(fid)
            for fid in (item.get("linked_finding_ids") or [])
            if str(fid) in finding_by_id
        ]
        if not linked_findings:
            rejected.append(
                {
                    "reason": "no_valid_linked_finding_ids",
                    "title": item.get("title"),
                    "claimed": item.get("linked_finding_ids"),
                }
            )
            continue

        linked_reviews: list[str] = []
        for fid in linked_findings:
            for rid in finding_by_id[fid].get("evidence_review_ids") or []:
                rid_s = str(rid)
                if rid_s not in linked_reviews:
                    linked_reviews.append(rid_s)

        claimed_reviews = [str(r) for r in (item.get("linked_review_ids") or [])]
        claimed_reviews = [r for r in claimed_reviews if r in linked_reviews]
        if claimed_reviews:
            linked_reviews = claimed_reviews

        if not linked_reviews:
            rejected.append(
                {
                    "reason": "no_linked_review_ids_after_validation",
                    "title": item.get("title"),
                    "linked_finding_ids": linked_findings,
                }
            )
            continue

        priority = str(item.get("priority") or "P1").upper()
        if priority not in {"P0", "P1", "P2"}:
            priority = "P1"

        version = str(item.get("version") or "vNext-1")
        if version not in {"vNext-1", "vNext-2", "Research"}:
            if priority == "P0":
                version = "vNext-1"
            elif priority == "P1":
                version = "vNext-2"
            else:
                version = "Research"

        acceptance = item.get("acceptance_criteria") or []
        if not isinstance(acceptance, list):
            acceptance = [str(acceptance)]
        non_goals = item.get("non_goals") or []
        if not isinstance(non_goals, list):
            non_goals = [str(non_goals)]

        requirements.append(
            {
                "req_id": str(item.get("req_id") or f"R{index + 1}"),
                "title": str(item.get("title") or "Untitled requirement")[:120],
                "description": str(item.get("description") or "")[:400],
                "user_problem": str(item.get("user_problem") or "")[:240],
                "priority": priority,
                "version": version,
                "linked_finding_ids": linked_findings,
                "linked_review_ids": linked_reviews,
                "acceptance_criteria": [str(x)[:180] for x in acceptance][:5],
                "non_goals": [str(x)[:120] for x in non_goals][:3],
                "origin": str(item.get("origin") or origin_default),
            }
        )

    version_plan = raw_prd.get("version_plan") or []
    if not isinstance(version_plan, list):
        version_plan = []

    req_ids_by_version: dict[str, list[str]] = {
        "vNext-1": [],
        "vNext-2": [],
        "Research": [],
    }
    for req in requirements:
        req_ids_by_version.setdefault(req["version"], []).append(req["req_id"])

    rebuilt_plan = []
    for version, focus_default in [
        ("vNext-1", "Highest-priority, high-evidence fixes"),
        ("vNext-2", "Important follow-ups"),
        ("Research", "Low-evidence or conflicting items to investigate"),
    ]:
        existing = next(
            (
                v
                for v in version_plan
                if isinstance(v, dict) and str(v.get("version")) == version
            ),
            None,
        )
        rebuilt_plan.append(
            {
                "version": version,
                "focus": str((existing or {}).get("focus") or focus_default)[:160],
                "req_ids": req_ids_by_version.get(version, []),
            }
        )

    prd = {
        "title": str(raw_prd.get("title") or "App Review Insights PRD")[:120],
        "background": str(raw_prd.get("background") or "")[:300],
        "goals": [str(x)[:160] for x in (raw_prd.get("goals") or [])][:5],
        "non_goals": [str(x)[:160] for x in (raw_prd.get("non_goals") or [])][:5],
        "version_plan": rebuilt_plan,
        "requirements": requirements,
        "risks": [str(x)[:160] for x in (raw_prd.get("risks") or [])][:5],
        "open_questions": [
            str(x)[:160] for x in (raw_prd.get("open_questions") or [])
        ][:5],
        "success_metrics": [
            str(x)[:160] for x in (raw_prd.get("success_metrics") or [])
        ][:5],
    }
    return prd, rejected


def plan_prd(
    findings: list[dict[str, Any]],
    goal: str | None = None,
    stats: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if not findings:
        return {
            "prd": {
                "title": "Insufficient findings for PRD",
                "background": "No grounded findings were available.",
                "goals": [],
                "non_goals": ["Do not invent requirements without evidence"],
                "version_plan": [],
                "requirements": [],
                "risks": ["Insufficient review evidence"],
                "open_questions": ["Collect more reviews or broaden analysis goal"],
                "success_metrics": [],
            },
            "planning_notes": "Skipped model PRD generation because findings were empty.",
            "validation": {"accepted": 0, "rejected": 0, "rejected_items": []},
            "model": None,
            "error": None,
        }

    client = MoonshotClient()
    messages = [
        {"role": "system", "content": PRD_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": build_prd_user_prompt(
                goal=goal,
                findings=_compact_findings(findings),
                stats=stats,
            ),
        },
    ]

    try:
        raw = client.chat_json(
            messages,
            temperature=0.1,
            retries=3,
            repair_hint=(
                "Keep at most 5 requirements; keep every string under 180 chars; "
                "escape quotes; no markdown; include prd.requirements array."
            ),
        )
        raw_prd = raw.get("prd")
        if not isinstance(raw_prd, dict):
            if isinstance(raw.get("requirements"), list):
                raw_prd = raw
            else:
                raise MoonshotError("Model JSON missing prd object")

        prd, rejected = _validate_prd(raw_prd, findings, origin_default="model")
        if not prd["requirements"]:
            raise MoonshotError("Model returned zero valid requirements after validation")

        notes = str(raw.get("planning_notes") or "")
        if rejected:
            notes = (
                (notes + " " if notes else "")
                + f"Rejected {len(rejected)} unsupported requirement(s) after validation."
            ).strip()

        return {
            "prd": prd,
            "planning_notes": notes,
            "validation": {
                "accepted": len(prd["requirements"]),
                "rejected": len(rejected),
                "rejected_items": rejected[:10],
            },
            "model": {
                "provider": "moonshot",
                "model": client.model,
                "temperature": 0.1,
            },
            "error": None,
        }
    except MoonshotError as exc:
        fallback = _fallback_prd_from_findings(findings, goal)
        prd, rejected = _validate_prd(fallback, findings, origin_default="rule")
        return {
            "prd": prd,
            "planning_notes": (
                "Used deterministic fallback PRD because Moonshot JSON failed: "
                f"{exc}"
            ),
            "validation": {
                "accepted": len(prd["requirements"]),
                "rejected": len(rejected),
                "rejected_items": rejected[:10],
            },
            "model": {
                "provider": "moonshot",
                "model": client.model,
                "temperature": 0.1,
                "fallback": "rule",
            },
            "error": str(exc),
        }
